import { askClaudeJSON } from './api'

// ticker: bare or .AX-suffixed symbol. earningsDate: 'YYYY-MM-DD'.
// Only generates within a 7-day lookahead window (and never for a date
// that's already passed) — outside that window this returns null so
// callers can decide not to show a preview affordance at all.
export async function generateEarningsPreview(ticker, earningsDate) {
  const daysUntil = Math.ceil((new Date(`${earningsDate}T00:00:00`) - new Date()) / 86400000)
  if (daysUntil > 7 || daysUntil < 0) return null

  // _v2: the v1 key holds previews generated by the old prompt, which
  // contained invented consensus figures and price targets. Those are cached
  // in real users' browsers and would keep being served indefinitely after
  // this fix, so the key is versioned to orphan them rather than trusted to
  // expire.
  const cacheKey = `maddex_earnings_preview_v2_${ticker}_${earningsDate}`
  const cached = localStorage.getItem(cacheKey)
  if (cached) {
    try { return JSON.parse(cached) } catch { /* fall through to regenerate */ }
  }

  // No quote is passed into the prompt.
  //
  // getMockFMPRow returns DEMO data — a synthesised price, P/E and 52-week
  // range. Feeding those in as "Current price" invited the model to reason
  // from a fabricated anchor and then report conclusions drawn from it as
  // though they described the real security.

  const prompt = `Generate a pre-earnings brief for ${ticker}, which reports in ${daysUntil} days.

YOU HAVE NO DATA FOR THIS COMPANY. That is deliberate, and it constrains what you may write.

Do NOT state, estimate or imply any of the following. This terminal has no
feed for them, so anything you produced would be invented:
- Consensus EPS or consensus revenue
- Analyst price targets, ratings, or the number of analysts covering the stock
- Historical beat/miss rates or "X of last Y quarters" claims
- Options-implied moves
- The current share price, market cap, P/E or 52-week range
- Any percentage, dollar figure or multiple whatsoever

Do NOT recommend an action. No buy, sell, hold, add, reduce, or "position
before the print". You are describing what the report will be about, not
advising anyone what to do about it.

What you CAN write, from general knowledge of the company and its industry:

Return JSON:
{
  "sector": "the sector this company operates in",
  "keyMetricsToWatch": ["metric 1", "metric 2", "metric 3"],
  "bullCase": "one sentence on what would constitute a good result, no figures",
  "bearCase": "one sentence on what would constitute a poor result, no figures",
  "keyQuestion": "The one question this earnings report will answer",
  "whyItMatters": "one sentence on why this result matters to the Australian market"
}
Return ONLY valid JSON. Every field is qualitative. If you find yourself writing a digit, you have misunderstood the task.`

  const preview = await askClaudeJSON(prompt, { maxTokens: 800 })
  try { localStorage.setItem(cacheKey, JSON.stringify(preview)) } catch { /* best-effort */ }
  return preview
}
