import { useState, useEffect } from 'react'
import { generateEarningsPreview } from '../../services/earningsPreviewService'
import { daysUntil } from '../../services/earningsCalendar'

export default function EarningsPreviewPanel({ ticker, earningsDate, companyName, onClose }) {
  const [status, setStatus] = useState('loading') // loading | ready | error | unavailable
  const [preview, setPreview] = useState(null)
  const [error, setError] = useState(null)
  const d = daysUntil(earningsDate)

  useEffect(() => {
    const t = setTimeout(async () => {
      try {
        const result = await generateEarningsPreview(ticker, earningsDate)
        if (!result) { setStatus('unavailable'); return }
        setPreview(result)
        setStatus('ready')
      } catch (e) {
        setError(e.message)
        setStatus('error')
      }
    }, 0)
    return () => clearTimeout(t)
  }, [ticker, earningsDate])

  return (
    <div className="modal-backdrop fixed inset-0 z-[100] bg-black/70 flex items-center justify-center p-4" onClick={onClose}>
      <div
        className="bg-terminal-panel border border-terminal-border w-full max-w-xl max-h-[85vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-4 py-2.5 border-b border-terminal-border flex-shrink-0">
          <div>
            <span className="text-2xs text-terminal-gold font-bold tracking-widest">EARNINGS PREVIEW · {ticker.replace('.AX', '')}</span>
            <div className="text-2xs text-terminal-text-dim">{companyName} · reports in {d} day{d === 1 ? '' : 's'}</div>
          </div>
          <button onClick={onClose} className="text-terminal-text-dim hover:text-terminal-red text-sm leading-none">✕</button>
        </div>

        <div className="flex-1 overflow-y-auto p-4">
          {status === 'loading' && (
            <div className="flex flex-col items-center justify-center py-16 gap-2">
              <div className="text-terminal-gold text-2xs tracking-widest animate-pulse">MADDENAI · PREVIEWING {ticker.replace('.AX', '')} EARNINGS...</div>
            </div>
          )}

          {status === 'unavailable' && (
            <div className="flex flex-col items-center justify-center py-16 gap-2 text-center px-6">
              <span className="text-terminal-text-dim text-2xs">This earnings date is more than 7 days away — previews generate closer to the report date.</span>
            </div>
          )}

          {status === 'error' && (
            <div className="flex flex-col items-center justify-center py-16 gap-2 text-center px-6">
              <span className="text-terminal-red text-lg">⚠</span>
              <div className="text-2xs text-terminal-red">{error}</div>
            </div>
          )}

          {status === 'ready' && preview && (
            <div className="space-y-4">
              {/* The consensus EPS, revenue, beat rate, implied move, analyst
                  count, price target and BUY/HOLD/SELL chip that used to sit
                  here were all generated by the model from no data at all,
                  and rendered in bright text beside figures that were real.
                  This terminal has no analyst-estimates feed, so the honest
                  version of this panel is qualitative only. */}
              <div className="border border-terminal-border p-3">
                <div className="text-2xs text-terminal-gold font-bold tracking-widest mb-1.5">KEY METRICS TO WATCH</div>
                <ul className="space-y-1">
                  {(preview.keyMetricsToWatch ?? []).map((m, i) => (
                    <li key={i} className="text-2xs text-terminal-text flex gap-2"><span className="text-terminal-gold">{i + 1}.</span>{m}</li>
                  ))}
                </ul>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="border border-terminal-green/30 p-2">
                  <div className="text-2xs text-terminal-green font-bold tracking-widest mb-1">BULL CASE</div>
                  <div className="text-2xs text-terminal-text">{preview.bullCase}</div>
                </div>
                <div className="border border-terminal-red/30 p-2">
                  <div className="text-2xs text-terminal-red font-bold tracking-widest mb-1">BEAR CASE</div>
                  <div className="text-2xs text-terminal-text">{preview.bearCase}</div>
                </div>
              </div>

              <div className="border border-terminal-border p-3">
                <div className="text-2xs text-terminal-gold font-bold tracking-widest mb-1">KEY QUESTION</div>
                <div className="text-2xs text-terminal-text italic">{preview.keyQuestion}</div>
              </div>

              {preview.whyItMatters && (
                <div className="border border-terminal-border p-3">
                  <div className="text-2xs text-terminal-gold font-bold tracking-widest mb-1">WHY IT MATTERS</div>
                  <div className="text-2xs text-terminal-text">{preview.whyItMatters}</div>
                </div>
              )}

              <div
                style={{
                  fontFamily: '"IBM Plex Mono", monospace',
                  fontSize: 9,
                  color: '#4A6080',
                  letterSpacing: '0.1em',
                  padding: '8px 0 0',
                  borderTop: '1px solid rgba(201,168,76,0.08)',
                }}
              >
                ⓘ AI-GENERATED · QUALITATIVE ONLY · NO CONSENSUS OR PRICE-TARGET DATA · NOT ADVICE
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
